"""Mitsuba 3 real-time path tracing server — WebRTC streaming.
Specular heightfield: custom BSDF computes normals from heightfield
differentials at ray-intersection time (1 um step size).
No PLY mesh, no precomputed textures.

Heightfield parameters (period, hmax, rotation_speed, reflectance, envmap path)
are live-configurable via POST /scene — the frontend owns the scene spec.

SPP and camera updates go through a single WebRTC data channel ("stats").
The client (offerer) creates the channel; the server (answerer) receives it
via pc.on("datachannel") and relays both directions.

Heightfield preview: GET /preview?... returns a PNG thumbnail generated by
heightfield.py (pure Python math, same logic as Dr.Jit version below).
heightfield.py is watched for changes and auto-reloaded.
"""

import asyncio
import importlib
import json
import logging
import math
import time
from pathlib import Path

import numpy as np
import mitsuba as mi
import drjit as dr

mi.set_variant("cuda_ad_rgb")

from aiohttp import web
from aiortc import RTCPeerConnection, RTCSessionDescription, VideoStreamTrack
from av import VideoFrame

import heightfield  # editable heightfield module (watched for changes)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mitsuba-stream")

SITE_DIR = Path(__file__).parent.resolve()

# ============================================================================
# Default scene spec (authoritative copy lives on the frontend)
# ============================================================================

DEFAULT_SCENE_SPEC = {
    "heightfield": {
        "period": 0.0003,       # 0.3 mm pyramid period
        "hmax": 0.00001,        # 0.01 mm pyramid height
        "fd_step": 0.000001,    # 1 um finite-difference step
        "rotation_speed": 0.0,  # rad/m — pyramid rotation per metre from center
        "reflectance": [0.95, 0.95, 0.95],
    },
    "envmap": "studio/studio_envmap.exr",
}

# ============================================================================
# Custom BSDF: specular heightfield mirror  (Dr.Jit evaluate inline)
# ============================================================================


def evaluate_drjit(x, y, period, hmax, rotation_speed=0.0):
    """Dr.Jit-compatible height field in physical coordinates (metres).
    Each pyramid is rotated by rotation_speed * distance_from_center (radians).
    Returns height in metres."""
    cell_u = dr.floor(x / period)
    cell_v = dr.floor(y / period)
    cell_cx = (cell_u + 0.5) * period
    cell_cy = (cell_v + 0.5) * period
    dist = dr.sqrt(cell_cx * cell_cx + cell_cy * cell_cy)
    angle = rotation_speed * dist

    u = x / period
    v = y / period
    u_local = u - cell_u
    v_local = v - cell_v

    uc = u_local - 0.5
    vc = v_local - 0.5
    cos_a = dr.cos(angle)
    sin_a = dr.sin(angle)
    ur = uc * cos_a - vc * sin_a + 0.5
    vr = uc * sin_a + vc * cos_a + 0.5

    du = dr.abs(ur - 0.5)
    dv = dr.abs(vr - 0.5)
    d = dr.maximum(du, dv)
    return hmax * dr.maximum(1.0 - 2.0 * d, 0.0)


class HeightfieldMirror(mi.BSDF):
    def __init__(self, props):
        mi.BSDF.__init__(self, props)

        hf_defaults = DEFAULT_SCENE_SPEC["heightfield"]

        def get_float(name, default):
            if props.has_property(name):
                return float(props[name])
            return default

        self.fd_step = get_float("fd_step", hf_defaults["fd_step"])
        self.height_scale = get_float("height_scale", 1.0)
        self.uv_scale_x = get_float("uv_scale_x", 1.0)
        self.uv_scale_y = get_float("uv_scale_y", 1.0)
        self.uv_offset_x = get_float("uv_offset_x", 0.0)
        self.uv_offset_y = get_float("uv_offset_y", 0.0)

        self.period = get_float("period", hf_defaults["period"])
        self.hmax   = get_float("hmax",   hf_defaults["hmax"])
        self.rotation_speed = get_float("rotation_speed", hf_defaults.get("rotation_speed", 0.0))

        if props.has_property("reflectance"):
            self.reflectance = mi.Color3f(props["reflectance"])
        else:
            self.reflectance = mi.Color3f(1.0)

        self.m_flags = mi.BSDFFlags.DeltaReflection | mi.BSDFFlags.FrontSide
        self.m_components = [self.m_flags]

    def height_gradient(self, si):
        """Central-difference gradient dh/du, dh/dv in UV space."""
        x = si.uv.x * self.uv_scale_x + self.uv_offset_x
        y = si.uv.y * self.uv_scale_y + self.uv_offset_y
        eps = self.fd_step

        h_xp = evaluate_drjit(x + eps, y, self.period, self.hmax, self.rotation_speed)
        h_xm = evaluate_drjit(x - eps, y, self.period, self.hmax, self.rotation_speed)
        h_yp = evaluate_drjit(x, y + eps, self.period, self.hmax, self.rotation_speed)
        h_ym = evaluate_drjit(x, y - eps, self.period, self.hmax, self.rotation_speed)

        dh_dx = (h_xp - h_xm) / (2.0 * eps)
        dh_dy = (h_yp - h_ym) / (2.0 * eps)

        dh_du = self.height_scale * self.uv_scale_x * dh_dx
        dh_dv = self.height_scale * self.uv_scale_y * dh_dy

        return dh_du, dh_dv

    def perturbed_normal(self, si):
        dh_du, dh_dv = self.height_gradient(si)
        dp_du = si.to_local(si.dp_du)
        dp_dv = si.to_local(si.dp_dv)
        displaced_du = mi.Vector3f(dp_du.x, dp_du.y, dh_du)
        displaced_dv = mi.Vector3f(dp_dv.x, dp_dv.y, dh_dv)
        N = dr.normalize(dr.cross(displaced_du, displaced_dv))
        N = dr.select(N.z < 0.0, -N, N)
        invalid = si.wi.z * dr.dot(si.wi, N) <= 0.0
        N = dr.select(invalid, mi.Vector3f(-N.x, -N.y, N.z), N)
        return N

    def sample(self, ctx, si, sample1, sample2, active=True):
        del sample1, sample2
        enabled = ctx.is_enabled(mi.BSDFFlags.DeltaReflection, 0)
        active = active & enabled & (si.wi.z > 0.0)
        N = self.perturbed_normal(si)
        cos_theta_m = dr.dot(si.wi, N)
        active = active & (cos_theta_m > 0.0)
        wo = 2.0 * cos_theta_m * N - si.wi
        active = active & (wo.z > 0.0)
        bs = mi.BSDFSample3f()
        bs.wo = dr.select(active, wo, mi.Vector3f(0.0))
        bs.pdf = dr.select(active, 1.0, 0.0)
        bs.eta = 1.0
        bs.sampled_component = mi.UInt32(0)
        bs.sampled_type = mi.UInt32(+mi.BSDFFlags.DeltaReflection)
        weight = dr.select(active, self.reflectance, mi.Color3f(0.0))
        return bs, weight

    def eval(self, ctx, si, wo, active=True):
        return mi.Color3f(0.0)

    def pdf(self, ctx, si, wo, active=True):
        return mi.Float(0.0)

    def eval_pdf(self, ctx, si, wo, active=True):
        return self.eval(ctx, si, wo, active), self.pdf(ctx, si, wo, active)

    def to_string(self):
        return "HeightfieldMirror[]"


mi.register_bsdf("heightfield_mirror", lambda props: HeightfieldMirror(props))
logger.info("Registered custom BSDF: heightfield_mirror")


# ============================================================================
# Video track
# ============================================================================


class MitsubaTrack(VideoStreamTrack):
    kind = "video"

    def __init__(self, renderer):
        super().__init__()
        self._renderer = renderer
        self._counter = 0

    async def recv(self):
        pts, time_base = await self.next_timestamp()
        t0 = time.time()
        frame_rgba = await self._renderer.render_frame()

        video_frame = VideoFrame.from_ndarray(frame_rgba, format="rgba")
        video_frame.pts = pts
        video_frame.time_base = time_base

        dt = (time.time() - t0) * 1000
        self._counter += 1
        if self._counter % 30 == 0:
            logger.info(
                "Frame %d: %dx%d, %.1fms, total_spp=%d",
                self._counter, self._renderer.width, self._renderer.height,
                dt, self._renderer.total_spp,
            )
        return video_frame


# ============================================================================
# Renderer
# ============================================================================


class MitsubaRenderer:
    def __init__(self, width=640, height=480):
        self.width = width
        self.height = height
        self.spp_per_frame = 4
        self._scene_spec = dict(DEFAULT_SCENE_SPEC)

        self._target    = np.array([0.0, 0.001, 0.0], dtype=np.float64)
        self._azimuth   = math.radians(0)
        self._elevation = math.radians(30)
        self._distance  = 0.4

        self._accum     = None
        self._total_spp = 0
        self._seed      = 0
        self._dirty     = True
        self._scene     = None
        self._build_scene()

        logger.info(
            "Renderer: %dx%d, spp_per_frame=%d, variant=%s",
            width, height, self.spp_per_frame, mi.variant(),
        )

    def _build_scene(self):
        az, el, dist = self._azimuth, self._elevation, self._distance
        x = dist * math.cos(el) * math.sin(az)
        y = dist * math.sin(el)
        z = dist * math.cos(el) * math.cos(az)
        origin = self._target + np.array([x, y, z])

        hf = self._scene_spec["heightfield"]

        scene_dict = {
            "type": "scene",
            "integrator": {"type": "path", "max_depth": 8},
            "sensor": {
                "type": "perspective",
                "near_clip": 0.0001,
                "far_clip": 100.0,
                "to_world": mi.ScalarTransform4f.look_at(
                    origin.tolist(),
                    self._target.tolist(),
                    [0.0, 1.0, 0.0],
                ),
                "fov": 45,
                "film": {
                    "type": "hdrfilm",
                    "width": self.width,
                    "height": self.height,
                    "pixel_format": "rgba",
                },
            },
            "envmap": {
                "type": "envmap",
                "filename": self._scene_spec["envmap"],
            },
            "ground": {
                "type": "rectangle",
                "bsdf": {
                    "type": "diffuse",
                    "reflectance": {"type": "rgb", "value": [0.5, 0.5, 0.5]},
                },
                "to_world": (
                    mi.ScalarTransform4f.translate([0, -0.05, 0])
                    .rotate([1, 0, 0], -90)
                    .scale([0.25, 0.25, 1.0])
                ),
            },
            "pyramid_plate": {
                "type": "rectangle",
                "bsdf": {
                    "type": "heightfield_mirror",
                    "uv_scale_x": 0.16,
                    "uv_scale_y": 0.08,
                    "uv_offset_x": -0.08,
                    "uv_offset_y": -0.04,
                    "period": hf["period"],
                    "hmax": hf["hmax"],
                    "fd_step": hf.get("fd_step", DEFAULT_SCENE_SPEC["heightfield"]["fd_step"]),
                    "rotation_speed": hf.get("rotation_speed", 0.0),
                    "reflectance": hf.get("reflectance", DEFAULT_SCENE_SPEC["heightfield"]["reflectance"]),
                },
                "to_world": (
                    mi.ScalarTransform4f.translate([0.0, 0.001, -0.0425])
                    .rotate([1, 0, 0], -90)
                    .scale([0.08, 0.04, 1.0])
                ),
            },
            "smooth_plate": {
                "type": "rectangle",
                "bsdf": {
                    "type": "conductor",
                    "material": "Ag",
                },
                "to_world": (
                    mi.ScalarTransform4f.translate([0.0, 0.001, 0.0425])
                    .rotate([1, 0, 0], -90)
                    .scale([0.08, 0.04, 1.0])
                ),
            },
        }

        self._scene = mi.load_dict(scene_dict)
        self._dirty = True

    def update_scene(self, spec):
        """Merge scene spec from the frontend. Only supplied keys are updated."""
        changed = False
        for section in ("heightfield",):
            if section in spec:
                incoming = spec[section]
                current = self._scene_spec.setdefault(section, {})
                for k, v in incoming.items():
                    if current.get(k) != v:
                        changed = True
                        current[k] = v
        if "envmap" in spec and spec["envmap"] != self._scene_spec.get("envmap"):
            self._scene_spec["envmap"] = spec["envmap"]
            changed = True
        if changed:
            self._build_scene()

    def get_scene_spec(self):
        return dict(self._scene_spec)

    def update_camera(self, azimuth, elevation, distance, target=None):
        changed = (
            abs(self._azimuth - azimuth) > 1e-6
            or abs(self._elevation - elevation) > 1e-6
            or abs(self._distance - distance) > 1e-6
        )
        if target is not None:
            self._target = np.array(target, dtype=np.float64)
        self._azimuth = azimuth
        self._elevation = elevation
        self._distance = max(0.05, min(5.0, distance))
        if changed:
            self._dirty = True
            self._build_scene()

    def update_resolution(self, width, height):
        self.width = max(160, min(3840, width))
        self.height = max(120, min(2160, height))
        self._dirty = True
        self._build_scene()

    async def render_frame(self):
        if self._dirty:
            self._accum = None
            self._total_spp = 0
            self._seed = 0
            self._dirty = False

        bmp = mi.render(self._scene, spp=self.spp_per_frame, seed=self._seed)
        self._seed += 1
        arr = np.array(bmp, copy=True)

        if self._accum is None:
            self._accum = np.zeros_like(arr, dtype=np.float64)

        self._accum += arr.astype(np.float64) * self.spp_per_frame
        self._total_spp += self.spp_per_frame
        result = (self._accum / self._total_spp).astype(np.float32)
        result = np.clip(result, 0.0, 1.0)
        result_uint8 = (result * 255).astype(np.uint8)
        return np.ascontiguousarray(result_uint8)

    @property
    def total_spp(self):
        return self._total_spp


# ============================================================================
# Heightfield file watching
# ============================================================================

_last_hf_mtime = 0.0


def check_hf_reload():
    """Check if heightfield.py was modified; reimport if so."""
    global _last_hf_mtime
    try:
        hf_path = Path(heightfield.__file__).resolve()
        mt = hf_path.stat().st_mtime
        if _last_hf_mtime == 0:
            _last_hf_mtime = mt
            return False
        if mt > _last_hf_mtime + 0.1:  # 100ms debounce
            _last_hf_mtime = mt
            return True
    except OSError:
        pass
    return False


def reload_heightfield():
    """Re-import heightfield module after file change."""
    global heightfield
    try:
        heightfield = importlib.reload(heightfield)
        logger.info("heightfield.py reloaded")
    except Exception as e:
        logger.warning("Failed to reload heightfield.py: %s", e)


async def hf_watchdog(interval=2.0):
    """Background task: periodically check for heightfield.py edits."""
    while True:
        await asyncio.sleep(interval)
        if check_hf_reload():
            reload_heightfield()


# ============================================================================
# HTTP / WebRTC
# ============================================================================

pcs = set()


async def handle_offer(request: web.Request):
    body = await request.json()
    offer = RTCSessionDescription(sdp=body["sdp"], type=body["type"])
    pc = RTCPeerConnection()
    pcs.add(pc)

    renderer = request.app["renderer"]
    data_channel_ref = []

    @pc.on("datachannel")
    def on_datachannel(channel):
        logger.info("Data channel opened: %s", channel.label)
        data_channel_ref.append(channel)
        @channel.on("message")
        def on_message(msg):
            try:
                data = json.loads(msg)
            except Exception:
                return
            if data.get("type") == "camera":
                renderer.update_camera(
                    azimuth=data.get("azimuth", renderer._azimuth),
                    elevation=data.get("elevation", renderer._elevation),
                    distance=data.get("distance", renderer._distance),
                    target=data.get("target"),
                )

    class MitsubaTrackDC(MitsubaTrack):
        async def recv(self):
            frame = await super().recv()
            if data_channel_ref and data_channel_ref[0].readyState == "open":
                msg = json.dumps({"total_spp": self._renderer.total_spp})
                data_channel_ref[0].send(msg)
            return frame

    track = MitsubaTrackDC(renderer)

    @pc.on("connectionstatechange")
    async def on_state():
        if pc.connectionState in ("failed", "closed", "disconnected"):
            pcs.discard(pc)

    pc.addTrack(track)
    await pc.setRemoteDescription(offer)
    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    resp = web.json_response({
        "sdp": pc.localDescription.sdp,
        "type": pc.localDescription.type,
    })
    resp.headers["Access-Control-Allow-Origin"] = "*"
    return resp


async def handle_camera(request: web.Request):
    body = await request.json()
    renderer = request.app["renderer"]
    renderer.update_camera(
        azimuth=body.get("azimuth", renderer._azimuth),
        elevation=body.get("elevation", renderer._elevation),
        distance=body.get("distance", renderer._distance),
    )
    resp = web.json_response({"ok": True, "total_spp": renderer.total_spp})
    resp.headers["Access-Control-Allow-Origin"] = "*"
    return resp


async def handle_config(request: web.Request):
    body = await request.json()
    renderer = request.app["renderer"]
    if "width" in body or "height" in body:
        renderer.update_resolution(body.get("width", 640), body.get("height", 480))
    if "spp" in body:
        renderer.spp_per_frame = body["spp"]
    resp = web.json_response({
        "ok": True,
        "width": renderer.width,
        "height": renderer.height,
        "spp_per_frame": renderer.spp_per_frame,
    })
    resp.headers["Access-Control-Allow-Origin"] = "*"
    return resp


async def get_state(request: web.Request):
    renderer = request.app["renderer"]
    resp = web.json_response({
        "azimuth": renderer._azimuth,
        "elevation": renderer._elevation,
        "distance": renderer._distance,
        "target": renderer._target.tolist(),
        "total_spp": renderer.total_spp,
        "width": renderer.width,
        "height": renderer.height,
    })
    resp.headers["Access-Control-Allow-Origin"] = "*"
    return resp


async def handle_scene_post(request: web.Request):
    body = await request.json()
    renderer = request.app["renderer"]
    renderer.update_scene(body)
    resp = web.json_response({"ok": True, "scene": renderer.get_scene_spec()})
    resp.headers["Access-Control-Allow-Origin"] = "*"
    return resp


async def handle_scene_get(request: web.Request):
    renderer = request.app["renderer"]
    resp = web.json_response(renderer.get_scene_spec())
    resp.headers["Access-Control-Allow-Origin"] = "*"
    return resp


async def handle_preview(request: web.Request):
    """GET /preview?period=0.0003&hmax=0.00001&rotation_speed=0.0&center_x=0&center_y=0&size_mm=2.0
    Returns a PNG thumbnail computed by heightfield.heightfield_preview()."""
    q = request.query
    try:
        period = float(q.get("period", 0.0003))
        hmax = float(q.get("hmax", 0.00001))
        rotation_speed = float(q.get("rotation_speed", 0.0))
        center_x = float(q.get("center_x", 0.0))
        center_y = float(q.get("center_y", 0.0))
        size_mm = float(q.get("size_mm", 2.0))
    except (ValueError, TypeError):
        return web.Response(status=400, text="Invalid query parameters")

    png = heightfield.heightfield_preview(
        width_px=128, height_px=128,
        period=period, hmax=hmax, rotation_speed=rotation_speed,
        center_x=center_x, center_y=center_y, size_mm=size_mm,
    )
    resp = web.Response(body=png, content_type="image/png")
    resp.headers["Access-Control-Allow-Origin"] = "*"
    resp.headers["Cache-Control"] = "no-cache"
    return resp


async def handle_options(request: web.Request):
    resp = web.Response()
    resp.headers["Access-Control-Allow-Origin"] = "*"
    resp.headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
    resp.headers["Access-Control-Allow-Headers"] = "Content-Type"
    return resp


async def handle_index(request: web.Request):
    return web.FileResponse(SITE_DIR / "index.html")


async def on_shutdown(app):
    await asyncio.gather(*(pc.close() for pc in pcs), return_exceptions=True)
    pcs.clear()


def create_app(renderer: MitsubaRenderer):
    app = web.Application()
    app["renderer"] = renderer
    app.router.add_post("/offer", handle_offer)
    app.router.add_post("/camera", handle_camera)
    app.router.add_post("/config", handle_config)
    app.router.add_post("/scene", handle_scene_post)
    app.router.add_get("/state", get_state)
    app.router.add_get("/scene", handle_scene_get)
    app.router.add_get("/preview", handle_preview)
    app.router.add_route("OPTIONS", "/{tail:.*}", handle_options)
    app.router.add_get("/", handle_index)
    app.router.add_static("/", SITE_DIR)
    app.on_shutdown.append(on_shutdown)
    return app


async def main():
    renderer = MitsubaRenderer(width=640, height=480)
    app = create_app(renderer)

    # Start heightfield file watcher
    asyncio.create_task(hf_watchdog())

    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, "127.0.0.1", 8766)
    await site.start()
    logger.info("Server running at http://127.0.0.1:8766")
    await asyncio.Event().wait()


if __name__ == "__main__":
    asyncio.run(main())
