# Generated by scripts/build-artifact-modules.mjs.
import json

ARTIFACT_MODULES = json.loads(r'''[
  {
    "id": "demo-stat",
    "importPath": "/artifact-modules/demo-stat.js",
    "description": "React component for a compact statistic card.",
    "exports": [
      "DemoStat",
      "mount"
    ],
    "importMap": {
      "imports": {
        "silverretort/runtime": "/artifact-modules/runtime.js",
        "silverretort/demo-stat": "/artifact-modules/demo-stat.js",
        "silverretort/circuit": "/artifact-modules/circuit.js"
      }
    },
    "jsxExample": "import React, { createRoot } from \"silverretort/runtime\";\nimport { DemoStat } from \"silverretort/demo-stat\";\ncreateRoot(document.getElementById(\"root\")).render(<DemoStat payload={payload} />);",
    "usage": "This is an ES module and does not define window globals. Merge importMap.imports into an import map before loading module scripts. Compiled JSX may import and compose named components from silverretort/demo-stat. Import React and createRoot from silverretort/runtime; browsers do not execute raw JSX, so compile JSX first. For a standalone mount, import { mount } from the same specifier and call mount(element, payload).",
    "payloadSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "label": {
          "type": "string",
          "description": "Short label shown above the primary value."
        },
        "value": {
          "type": [
            "string",
            "number"
          ],
          "description": "Primary metric value."
        },
        "unit": {
          "type": "string",
          "description": "Unit displayed next to the primary value."
        },
        "description": {
          "type": "string",
          "description": "Supporting sentence below the primary value."
        },
        "trend": {
          "type": "object",
          "properties": {
            "label": {
              "type": "string"
            },
            "tone": {
              "$ref": "#/definitions/TrendTone"
            }
          },
          "additionalProperties": false,
          "description": "Compact trend badge shown in the top-right corner."
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string"
              },
              "value": {
                "type": [
                  "string",
                  "number"
                ]
              }
            },
            "required": [
              "label",
              "value"
            ],
            "additionalProperties": false
          },
          "description": "Secondary stats shown below the description."
        }
      },
      "additionalProperties": false,
      "definitions": {
        "TrendTone": {
          "type": "string",
          "enum": [
            "up",
            "down",
            "neutral"
          ]
        }
      }
    }
  },
  {
    "id": "circuit",
    "importPath": "/artifact-modules/circuit.js",
    "description": "Interactive RF/electrical circuit React component and circuit helpers.",
    "exports": [
      "Circuit",
      "mount",
      "DEFAULT_CIRCUIT",
      "normalizeCircuitData"
    ],
    "importMap": {
      "imports": {
        "silverretort/runtime": "/artifact-modules/runtime.js",
        "silverretort/demo-stat": "/artifact-modules/demo-stat.js",
        "silverretort/circuit": "/artifact-modules/circuit.js"
      }
    },
    "jsxExample": "import React, { createRoot } from \"silverretort/runtime\";\nimport { Circuit } from \"silverretort/circuit\";\ncreateRoot(document.getElementById(\"root\")).render(<Circuit data={payload} />);",
    "usage": "This is an ES module and does not define window globals. Merge importMap.imports into an import map before loading module scripts. Compiled JSX may import and compose named components from silverretort/circuit. Import React and createRoot from silverretort/runtime; browsers do not execute raw JSX, so compile JSX first. For a standalone mount, import { mount } from the same specifier and call mount(element, payload).",
    "payloadSchema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "blocks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Block"
          }
        },
        "links": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Link"
          }
        }
      },
      "required": [
        "blocks",
        "links"
      ],
      "additionalProperties": false,
      "definitions": {
        "Block": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "pins": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/BlockPin"
              }
            },
            "position": {
              "$ref": "#/definitions/Point"
            },
            "rotation": {
              "$ref": "#/definitions/Rotation"
            },
            "type": {
              "$ref": "#/definitions/CircuitBlockType"
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "id"
          ],
          "additionalProperties": false
        },
        "BlockPin": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "Point": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "additionalProperties": false
        },
        "Rotation": {
          "type": "number",
          "enum": [
            0,
            90,
            180,
            270
          ]
        },
        "CircuitBlockType": {
          "type": "string",
          "enum": [
            "capacitor",
            "ground",
            "inductor",
            "port",
            "resistor",
            "snp"
          ]
        },
        "Link": {
          "type": "object",
          "properties": {
            "from": {
              "$ref": "#/definitions/LinkPin"
            },
            "points": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Point"
              }
            },
            "to": {
              "$ref": "#/definitions/LinkPin"
            }
          },
          "required": [
            "from",
            "to"
          ],
          "additionalProperties": false
        },
        "LinkPin": {
          "anyOf": [
            {
              "$ref": "#/definitions/BlockLinkPin"
            },
            {
              "$ref": "#/definitions/PointLinkPin"
            }
          ]
        },
        "BlockLinkPin": {
          "type": "object",
          "properties": {
            "kind": {
              "type": "string",
              "const": "pin"
            },
            "node": {
              "type": "string"
            },
            "pin": {
              "type": "number"
            }
          },
          "required": [
            "node",
            "pin"
          ],
          "additionalProperties": false
        },
        "PointLinkPin": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            },
            "kind": {
              "type": "string",
              "const": "point"
            }
          },
          "required": [
            "kind",
            "x",
            "y"
          ],
          "additionalProperties": false
        }
      }
    }
  }
]''')
